export const videos = [
    {
        id: 1,
        title: "Become a Web Developer in 2022",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    },
    {
        id: 2,
        title: "how to become a blockchain developer",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    },
    {
        id: 3,
        title: "Reactjs for Beginners",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    },
    {
        id: 4,
        title: "blockchain for beginners",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    },
    {
        id: 5,
        title: "Become a Web Developer in 2020",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    },
    {
        id: 6,
        title: "Become a Web Developer in 2020",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    }, {
        id: 7,
        title: "Become a Web Developer in 2020",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    },
    {
        id: 8,
        title: "Become a Web Developer in 2020",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    },
    {
        id: 9,
        title: "Become a Web Developer in 2020",
        channel: "Code with Edgar",
        image: "https://i.ytimg.com/vi/QG2zgCeo_EI/hqdefault.jpg",
        views: "1,001,023",
        timestamp: "3 days ago",
    }
];